import { describe, expect, it } from "vitest";
import { DEFAULT_SCENARIOS } from "@/config/scenarios";
import type { MetricResult } from "@/lib/finance/returns";
import { analyzePropertyFixture } from "./fixtures/analyze-phase1-property";
import { createPropertyFixture, createPropertyFixtures, PROPERTY_FIXTURE_IDS } from "./fixtures/phase1-properties";

const analyze = (id: (typeof PROPERTY_FIXTURE_IDS)[number]) => analyzePropertyFixture(createPropertyFixture(id));
const value = (metric: MetricResult) => {
  expect(metric.status).toBe("ok");
  if (metric.status !== "ok") throw new Error("Expected an available financial metric");
  return metric.value;
};

describe("reusable Phase 1 property fixtures", () => {
  it("provides all ten IDs and independent nested inputs for every consumer", () => {
    expect(createPropertyFixtures().map(f => f.id)).toEqual(PROPERTY_FIXTURE_IDS);
    const original = createPropertyFixtures();
    const changed = createPropertyFixtures();
    for (const f of changed) {
      f.property.expected_monthly_rent = 0;
      f.acquisitionCosts.purchase_price = 1;
      f.operatingExpenses.annual_maintenance_fee = 0;
      f.financing.loan_tenure_years = 1;
      f.scenarios.base.vacancyMonths = 12;
      f.description = "Changed locally";
    }
    expect(createPropertyFixtures()).toEqual(original);
    expect(DEFAULT_SCENARIOS.base.vacancyMonths).toBe(1);
  });

  it.each(PROPERTY_FIXTURE_IDS)("%s is deterministic, does not mutate inputs, and uses only Phase 1 evidence", id => {
    const fixture = createPropertyFixture(id);
    const before = structuredClone(fixture);
    const result = analyzePropertyFixture(fixture);
    expect(analyzePropertyFixture(fixture)).toEqual(result);
    expect(fixture).toEqual(before);
    expect(fixture.synthetic).toBe(true);
    for (const module of Object.values(fixture.futureModules)) {
      expect(module).toEqual({ status: "unavailable", placeholderOnly: true, evidence: null });
    }
    expect(result.invest.categories.map(c => c.key)).toEqual([
      "net_rental_yield", "gross_rental_yield", "monthly_cash_flow",
      "cash_on_cash_return", "break_even_occupancy", "financing_resilience",
    ]);
    for (const key of ["rental_comparables", "transaction_evidence", "building_inspection", "legal_verification", "external_data_quality"]) {
      expect(result.confidence.factors.find(f => f.key === key)).toMatchObject({
        status: "not-available-in-phase", weight: 0, contribution: 0, deduction: 0,
      });
    }
    expect(result.redFlags.rules.map(r => r.key).sort()).toEqual([
      "negative_base_cash_flow", "very_low_data_confidence", "rent_not_verified", "valuation_below_target",
      "high_financed_break_even", "important_information_missing", "operating_costs_missing",
      "acquisition_costs_missing", "financing_incomplete", "low_cash_on_cash",
    ].sort());
    expect(result.recommendation.critical_risks).toEqual(result.redFlags.flags
      .filter(f => f.severity === "critical").map(({ risk_name, actual_value }) => ({ risk_name, actual_value })));
  });

  // Fixed expectations from hand-worked inputs, not values generated by the engines.
  // RM 240,000 at 4% for 360 months => RM 1,145.80/month; cash invested = RM 90,000.
  it.each([
    { id: "P01", expenses: 6000, rent: 38500, noi: 32500, cash: 1562.53, annual: 18750.4, gross: 14, net: 9.85, coc: 20.83, occupancy: 47.02, score: 100 },
    { id: "P02", expenses: 6000, rent: 16500, noi: 10500, cash: -270.8, annual: -3249.6, gross: 6, net: 3.18, coc: -3.61, occupancy: 109.72, score: 28.04 },
    { id: "P03", expenses: 6000, rent: 14000, noi: 8000, cash: -479.13, annual: -5749.6, gross: 14, net: 2.42, coc: -6.39, occupancy: 47.02, score: 36.74 },
    { id: "P04", expenses: 27600, rent: 38500, noi: 10900, cash: -237.47, annual: -2849.6, gross: 14, net: 3.3, coc: -3.17, occupancy: 98.45, score: 34.57 },
  ] as const)("$id has independently calculated financial results and scoring", row => {
    const r = analyze(row.id);
    expect(r.acquisition).toMatchObject({ status: "complete", total: 330000 });
    expect(r.operatingExpenses).toMatchObject({ status: "complete", total: row.expenses });
    expect(r.financing).toMatchObject({ loanAmount: 240000, downPayment: 60000, calculatedMonthlyInstalment: 1145.8, annualDebtService: 13749.6 });
    for (const [key, expected] of Object.entries({
      effectiveAnnualRent: row.rent, netOperatingIncome: row.noi, monthlyCashFlow: row.cash,
      annualCashFlow: row.annual, grossRentalYield: row.gross, netRentalYield: row.net,
      cashOnCashReturn: row.coc, financedBreakEvenOccupancy: row.occupancy,
      acquisitionCostsNotFinanced: 30000, initialCashInvested: 90000,
    })) {
      expect(r.returns[key as keyof typeof r.returns]).toEqual({ status: "ok", value: expected });
    }
    expect(r.invest).toMatchObject({ status: "complete", data_coverage: 1, overall_score: row.score });
    expect(r.confidence.score).toBe(100); // Bad returns do not mean unreliable data.
  });

  it.each([
    ["P01", "BUY CANDIDATE", []],
    ["P02", "REJECT", ["negative_base_cash_flow", "high_financed_break_even"]],
    ["P03", "NEGOTIATE", ["negative_base_cash_flow"]],
    ["P04", "REJECT", ["negative_base_cash_flow", "high_financed_break_even"]],
    ["P05", "NEGOTIATE", ["valuation_below_target"]],
    ["P06", "INSUFFICIENT DATA", ["rent_not_verified", "important_information_missing"]],
    ["P07", "INSUFFICIENT DATA", ["important_information_missing"]],
    ["P08", "BUY CANDIDATE", []],
    ["P09", "BUY CANDIDATE", []],
    ["P10", "WATCHLIST", ["rent_not_verified"]],
  ] as const)("%s recommends %s with exactly the supported critical flags", (id, decision, critical) => {
    const r = analyze(id);
    expect(r.recommendation.recommendation).toBe(decision);
    expect(r.redFlags.flags.filter(f => f.severity === "critical").map(f => f.key).sort()).toEqual([...critical].sort());
    expect(r.redFlags.criticalCount).toBe(critical.length);
    expect(r.recommendation.reasons.length).toBeGreaterThan(0);
  });

  it.each(PROPERTY_FIXTURE_IDS.filter(id => id !== "P06" && id !== "P07"))("%s orders bear/base/bull cash flow and scores the actual bear result", id => {
    const r = analyze(id);
    const bear = value(r.scenarios.bear.returns.monthlyCashFlow);
    const base = value(r.scenarios.base.returns.monthlyCashFlow);
    const bull = value(r.scenarios.bull.returns.monthlyCashFlow);
    expect(bear).toBeLessThan(base);
    expect(base).toBeLessThan(bull);
    expect(r.invest.categories.find(c => c.key === "financing_resilience")?.raw_value).toBe(bear);
  });

  it("P01 applies rent, vacancy, repair and interest stress assumptions together", () => {
    const { bear, bull } = analyze("P01").scenarios;
    expect(bear.assumptions).toMatchObject({ monthlyRent: 3150, occupiedMonths: 9, annualRepairReserve: 1500, interestRatePercent: 6 });
    expect(bear.annualOperatingExpenses).toBe(6300);
    expect(bear.annualDebtService).toBe(17267.04);
    expect(value(bear.returns.netOperatingIncome)).toBe(22050);
    expect(value(bear.returns.monthlyCashFlow)).toBe(398.58);
    expect(bull.assumptions).toMatchObject({ monthlyRent: 3675, occupiedMonths: 11.5, annualRepairReserve: 1080, interestRatePercent: 4 });
    expect(value(bull.returns.monthlyCashFlow)).toBe(1886.08);
  });

  it("P03 reduces collected rent, not potential yield or data confidence", () => {
    const strong = analyze("P01");
    const vacant = analyze("P03");
    expect(vacant.scenarios.base.assumptions.occupiedMonths).toBe(4);
    expect(vacant.returns.potentialAnnualRent).toEqual(strong.returns.potentialAnnualRent);
    expect(vacant.returns.grossRentalYield).toEqual(strong.returns.grossRentalYield);
    expect(vacant.returns.financedBreakEvenOccupancy).toEqual(strong.returns.financedBreakEvenOccupancy);
    expect(vacant.confidence).toEqual(strong.confidence);
    expect(vacant.recommendation.rules_triggered).toContain("critical_flag:negative_base_cash_flow");
  });

  it("P04 maintenance costs reduce NOI by the known expense increase", () => {
    const strong = analyze("P01");
    const costly = analyze("P04");
    expect(value(strong.returns.netOperatingIncome) - value(costly.returns.netOperatingIncome)).toBe(21600);
    expect(costly.invest.overall_score).toBeLessThan(strong.invest.overall_score!);
    expect(costly.redFlags.flags.find(f => f.key === "high_financed_break_even")).toMatchObject({ severity: "critical", evidence_status: "Calculated" });
  });

  it("P05 uses only the bank-valuation gap to negotiate despite strong returns", () => {
    const r = analyze("P05");
    expect(r.returns).toEqual(analyze("P01").returns);
    expect(r.invest.overall_score).toBe(100);
    expect(r.confidence.score).toBe(100);
    expect(r.redFlags.flags.map(f => f.key)).toEqual(["valuation_below_target"]);
    expect(r.recommendation.rules_triggered).toContain("critical_flag:valuation_below_target");
  });

  it.each(["P06", "P07"] as const)("%s propagates missing evidence through every scenario and blocks scoring/BUY", id => {
    const r = analyze(id);
    for (const scenario of Object.values(r.scenarios)) {
      for (const metric of ["netOperatingIncome", "netRentalYield", "monthlyCashFlow", "annualCashFlow", "cashOnCashReturn", "financedBreakEvenOccupancy"] as const) {
        expect(scenario.returns[metric]).toMatchObject({ status: "incomplete", value: null });
      }
    }
    expect(r.invest).toMatchObject({ status: "insufficient-data", overall_score: null });
    expect(r.invest.categories.find(c => c.key === "monthly_cash_flow")).toMatchObject({ raw_score: null, data_availability_status: "missing" });
    expect(r.redFlags.rules.find(f => f.key === "negative_base_cash_flow")?.state).toBe("UNCHECKED");
    expect(r.redFlags.rules.find(f => f.key === "high_financed_break_even")?.state).toBe("UNCHECKED");
    expect(r.recommendation.rules_triggered).toContain("missing_financial_results");
    expect(r.recommendation.missing_information).toContain(id === "P06" ? "Expected monthly rent" : "Maintenance fee");
    expect(r.confidence.score).toBe(id === "P06" ? 72 : 95.93);
  });

  it("P07 keeps partial expense totals separate from usable totals and confirmed zero", () => {
    const fixture = createPropertyFixture("P07");
    const missing = analyzePropertyFixture(fixture);
    expect(missing.operatingExpenses).toMatchObject({ status: "partial", total: 3600, missingFields: ["annual_maintenance_fee"] });
    expect(missing.operatingExpenses.zeroFields).not.toContain("annual_maintenance_fee");
    expect(value(missing.returns.grossRentalYield)).toBe(14);
    fixture.operatingExpenses.annual_maintenance_fee = 0;
    const zero = analyzePropertyFixture(fixture);
    expect(zero.operatingExpenses.status).toBe("complete");
    expect(zero.operatingExpenses.zeroFields).toContain("annual_maintenance_fee");
    expect(zero.returns.monthlyCashFlow.status).toBe("ok");
    expect(zero.confidence.score).toBe(100);
  });

  it.each(["P08", "P09"] as const)("%s placeholder cannot change financials, scoring, confidence, flags or recommendations", id => {
    const f = createPropertyFixture(id);
    expect(f.placeholderFocus).toBe(id === "P08" ? "legal" : "location");
    expect(analyzePropertyFixture(f)).toEqual(analyze("P01"));
    expect(analyzePropertyFixture(f).recommendation.rules_triggered).toContain("due_diligence_required");
  });

  it("P10 separates confidence from returns and scores, withholding BUY until evidence improves", () => {
    const strong = analyze("P01");
    const uncertain = analyze("P10");
    expect(uncertain.scenarios).toEqual(strong.scenarios);
    expect(uncertain.invest).toEqual(strong.invest);
    // Missing rent evidence 25 + unverified financing 10 + absent valuation 10.
    expect(uncertain.confidence).toMatchObject({ score: 55, band: { key: "low" } });
    expect(uncertain.redFlags.rules.find(f => f.key === "valuation_below_target")?.state).toBe("UNCHECKED");
    expect(uncertain.recommendation.rules_triggered).toContain("confidence_below_watchlist_threshold");
    expect(uncertain.recommendation.rules_triggered).toContain("critical_flag:rent_not_verified");
  });
});
