/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAnalysisNewRouteImport } from './routes/_authenticated/analysis/new'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated/properties/$id'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysisNewRoute =
  AuthenticatedAnalysisNewRouteImport.update({
    id: '/_authenticated/analysis/new',
    path: '/analysis/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/_authenticated/properties/',
    path: '/properties/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/_authenticated/properties/$id',
    path: '/properties/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/analysis/new': typeof AuthenticatedAnalysisNewRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/analysis/new': typeof AuthenticatedAnalysisNewRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/analysis/new': typeof AuthenticatedAnalysisNewRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/settings'
    | '/analysis/new'
    | '/properties/$id'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/settings'
    | '/analysis/new'
    | '/properties/$id'
    | '/properties'
  id:
    | '__root__'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_authenticated/settings'
    | '/_authenticated/analysis/new'
    | '/_authenticated/properties/$id'
    | '/_authenticated/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAnalysisNewRoute: typeof AuthenticatedAnalysisNewRoute
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analysis/new': {
      id: '/_authenticated/analysis/new'
      path: '/analysis/new'
      fullPath: '/analysis/new'
      preLoaderRoute: typeof AuthenticatedAnalysisNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAnalysisNewRoute: AuthenticatedAnalysisNewRoute,
  AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
